// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2_PUBLIC_20260605 program: libSceHttp.sprx
// Analyzed provider SHA-256: fdb6ddc34e9d8c566421511c693294ca93ab1636f797f8fc705588b678fb1f6a
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class HttpLleExports
{
    // Ghidra entry 00020f90; body addresses 298.
    [SysAbiExport(
        Nid = "YuOW3dDAKYc",
        ExportName = "sceHttpUriEscape",
        Target = Generation.Gen5,
        LibraryName = "libSceHttp",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] Http LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
