// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2_PUBLIC_20260605 program: libSceJson2.sprx
// Analyzed provider SHA-256: 1ca532e78ed5e02c553e99ebb01751df6baaefa0bd6481c69db56e08536ba06c
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class Json2LleExports
{
    // Ghidra entry 00004430; body addresses 14.
    [SysAbiExport(
        Nid = "-NxEk7XLkDY",
        ExportName = "_ZN3sce4Json5Value11referObjectEv",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    // Ghidra entry 00001eb0; body addresses 70.
    [SysAbiExport(
        Nid = "3xUXnmUkXfo",
        ExportName = "_ZN3sce4Json5ValueC1ERKNS0_6ObjectE",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    // Ghidra entry 0000d520; body addresses 83.
    [SysAbiExport(
        Nid = "5JmzZt8twAo",
        ExportName = "_ZN3sce4Json6ObjectD1Ev",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    // Ghidra entry 0000e450; body addresses 575.
    [SysAbiExport(
        Nid = "ERuf9y0DY84",
        ExportName = "_ZN3sce4Json6ObjectixERKNS0_6StringE",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    // Ghidra entry 0000ad30; body addresses 15.
    [SysAbiExport(
        Nid = "EUH+EmT-v9E",
        ExportName = "_ZNK3sce4Json6String6lengthEv",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    // Ghidra entry 000048f0; body addresses 350.
    [SysAbiExport(
        Nid = "IlsmvBtMkak",
        ExportName = "_ZNK3sce4Json5Value9getObjectEv",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    // Ghidra entry 0000d220; body addresses 251.
    [SysAbiExport(
        Nid = "OJPTonqdg0I",
        ExportName = "_ZN3sce4Json6ObjectC1Ev",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    // Ghidra entry 000038d0; body addresses 143.
    [SysAbiExport(
        Nid = "R7FDWtcN6f8",
        ExportName = "_ZN3sce4Json5Value9serializeERNS0_6StringE",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    // Ghidra entry 0000d320; body addresses 218.
    [SysAbiExport(
        Nid = "a+W7HHlwpBs",
        ExportName = "_ZN3sce4Json6ObjectC1ERKS1_",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    // Ghidra entry 0000c180; body addresses 30.
    [SysAbiExport(
        Nid = "bAM9Qwofus0",
        ExportName = "_ZNK3sce4Json5Array4backEv",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    // Ghidra entry 0000af70; body addresses 139.
    [SysAbiExport(
        Nid = "cn9svYGWKDQ",
        ExportName = "_ZN3sce4Json6StringaSERKS1_",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    // Ghidra entry 00004420; body addresses 14.
    [SysAbiExport(
        Nid = "nM5XqdeXFPw",
        ExportName = "_ZN3sce4Json5Value10referArrayEv",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    // Ghidra entry 0000d6d0; body addresses 13.
    [SysAbiExport(
        Nid = "oH8aBmLU+fc",
        ExportName = "_ZN3sce4Json6Object5clearEv",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    // Ghidra entry 0000c1c0; body addresses 16.
    [SysAbiExport(
        Nid = "rQGJeNjOuUk",
        ExportName = "_ZNK3sce4Json5Array4sizeEv",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    // Ghidra entry 0000e400; body addresses 71.
    [SysAbiExport(
        Nid = "urOpESTBZmo",
        ExportName = "_ZN3sce4Json6ObjectaSERKS1_",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    // Ghidra entry 0000c240; body addresses 419.
    [SysAbiExport(
        Nid = "zQtLRTqceMY",
        ExportName = "_ZN3sce4Json5Array9push_backERKNS0_5ValueE",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] Json2 LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
