// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2_PUBLIC_20260605 program: libSceJson2.sprx
// Analyzed provider SHA-256: 1ca532e78ed5e02c553e99ebb01751df6baaefa0bd6481c69db56e08536ba06c
// Each registration prefers the loaded guest export. When that provider is
// unavailable, the individual semantic HLE handlers preserve object state.

using SharpEmu.HLE;
using SharpEmu.Libs.Json;

namespace SharpEmu.Libs.Lle;

public static class Json2LleExports
{
    // Ghidra entry 00001eb0; body addresses 70.
    [SysAbiExport(
        Nid = "3xUXnmUkXfo",
        ExportName = "_ZN3sce4Json5ValueC1ERKNS0_6ObjectE",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    public static int ValueObjectConstructor(CpuContext ctx) =>
        JsonExports.ValueObjectConstructor(ctx);

    // Ghidra entry 0000d520; body addresses 83.
    [SysAbiExport(
        Nid = "5JmzZt8twAo",
        ExportName = "_ZN3sce4Json6ObjectD1Ev",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    public static int ObjectDestructor(CpuContext ctx) =>
        JsonExports.ObjectDestructor(ctx);

    // Ghidra entry 0000ad30; body addresses 15.
    [SysAbiExport(
        Nid = "EUH+EmT-v9E",
        ExportName = "_ZNK3sce4Json6String6lengthEv",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    public static int StringLength(CpuContext ctx) =>
        JsonExports.StringLength(ctx);

    // Ghidra entry 000048f0; body addresses 350.
    [SysAbiExport(
        Nid = "IlsmvBtMkak",
        ExportName = "_ZNK3sce4Json5Value9getObjectEv",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    public static int ValueGetObject(CpuContext ctx) =>
        JsonExports.ValueGetObject(ctx);

    // Ghidra entry 0000d220; body addresses 251.
    [SysAbiExport(
        Nid = "OJPTonqdg0I",
        ExportName = "_ZN3sce4Json6ObjectC1Ev",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    public static int ObjectDefaultConstructor(CpuContext ctx) =>
        JsonExports.ObjectDefaultConstructor(ctx);

    // Ghidra entry 0000d320; body addresses 218.
    [SysAbiExport(
        Nid = "a+W7HHlwpBs",
        ExportName = "_ZN3sce4Json6ObjectC1ERKS1_",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    public static int ObjectCopyConstructor(CpuContext ctx) =>
        JsonExports.ObjectCopyConstructor(ctx);

    // Ghidra entry 0000af70; body addresses 139.
    [SysAbiExport(
        Nid = "cn9svYGWKDQ",
        ExportName = "_ZN3sce4Json6StringaSERKS1_",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    public static int StringAssignment(CpuContext ctx) =>
        JsonExports.StringAssignment(ctx);

    // Ghidra entry 0000d6d0; body addresses 13.
    [SysAbiExport(
        Nid = "oH8aBmLU+fc",
        ExportName = "_ZN3sce4Json6Object5clearEv",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    public static int ObjectClear(CpuContext ctx) =>
        JsonExports.ObjectClear(ctx);

    // Ghidra entry 0000c1c0; body addresses 16.
    [SysAbiExport(
        Nid = "rQGJeNjOuUk",
        ExportName = "_ZNK3sce4Json5Array4sizeEv",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    public static int ArraySize(CpuContext ctx) =>
        JsonExports.ArraySize(ctx);

    // Ghidra entry 0000e400; body addresses 71.
    [SysAbiExport(
        Nid = "urOpESTBZmo",
        ExportName = "_ZN3sce4Json6ObjectaSERKS1_",
        Target = Generation.Gen5,
        LibraryName = "libSceJson2",
        PreferLle = true)]
    public static int ObjectAssignment(CpuContext ctx) =>
        JsonExports.ObjectAssignment(ctx);

    // Retained without registrations so the provider-catalog fail-closed
    // invariant can still be tested independently.
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] Json2 LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
