#!/usr/bin/env python3
"""Generate fail-closed, LLE-preferred SysAbi registrations from Ghidra evidence."""

from __future__ import annotations

import argparse
import base64
import csv
import hashlib
import json
from pathlib import Path


NID_SUFFIX = bytes.fromhex("518d64a635ded8c1e6b039b1c3e55230")


def csharp_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\r", "\\r")
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def name_to_nid(symbol: str) -> str:
    digest = hashlib.sha1(symbol.encode("utf-8") + NID_SUFFIX).digest()
    return base64.b64encode(digest[:8][::-1]).decode("ascii").rstrip("=").replace("/", "-")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("queue", type=Path)
    parser.add_argument("evidence", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--component", required=True)
    parser.add_argument("--namespace", required=True)
    parser.add_argument("--class-name", required=True)
    parser.add_argument("--library", required=True)
    parser.add_argument("--allow-unnamed", action="store_true")
    parser.add_argument("--exclude-nid", action="append", default=[])
    parser.add_argument("--log-env", default="SHARPEMU_LOG_IMPORTS")
    parser.add_argument("--log-label")
    args = parser.parse_args()

    excluded_nids = set(args.exclude_nid)
    with args.queue.open(newline="") as handle:
        component_rows = [
            row for row in csv.DictReader(handle)
            if row.get("component") == args.component
        ]
    component_nids = {row["nid"] for row in component_rows}
    unknown_exclusions = excluded_nids - component_nids
    if unknown_exclusions:
        parser.error(f"excluded NIDs are not in the component queue: {sorted(unknown_exclusions)}")
    rows = [row for row in component_rows if row["nid"] not in excluded_nids]
    if not rows:
        parser.error(f"component has no queue rows: {args.component}")

    by_nid = {row["nid"]: row for row in rows}
    if len(by_nid) != len(rows):
        parser.error("queue component contains duplicate NIDs")
    if any(row.get("library") != args.library for row in rows):
        parser.error("queue rows do not all use the requested library")
    if not args.allow_unnamed and any(not row.get("catalog_symbol") for row in rows):
        parser.error("every generated registration requires an explicit catalog symbol")
    for row in rows:
        symbol = row.get("catalog_symbol")
        if symbol and name_to_nid(symbol) != row["nid"]:
            parser.error(
                f"catalog symbol/NID mismatch: {symbol!r} -> {name_to_nid(symbol)}, "
                f"queue has {row['nid']}"
            )

    evidence = json.loads(args.evidence.read_text())
    if evidence.get("format") != "sharpemu-ghidra-selected-nid-functions-v1":
        parser.error("unsupported or non-Ghidra evidence format")
    functions = {row["nid"]: row for row in evidence.get("functions", [])}
    target_nids = set(by_nid)
    if set(functions) != target_nids:
        missing = sorted(target_nids - set(functions))
        extra = sorted(set(functions) - target_nids)
        parser.error(f"Ghidra evidence set mismatch: missing={missing} extra={extra}")
    if evidence.get("target_count") != len(rows) or evidence.get("function_count") != len(rows):
        parser.error("Ghidra evidence counts do not match the queue")
    if evidence.get("missing") or evidence.get("without_functions"):
        parser.error("Ghidra evidence reports incomplete function coverage")
    for nid, function in functions.items():
        if not function.get("function_present"):
            parser.error(f"Ghidra did not create a function for {nid}")
        if function.get("symbol_address") != function.get("function_entry"):
            parser.error(f"Ghidra symbol/function entry mismatch for {nid}")
        if (int(function.get("function_body_addresses", 0)) <= 0 and
                int(function.get("function_body_bytes", 0)) <= 0):
            parser.error(f"Ghidra function body is empty for {nid}")

    # REUSE-IgnoreStart
    # The following licensing text is emitted into generated C# source and is
    # not the licensing declaration for this Python file. Its licensing is
    # recorded in REUSE.toml with the other files imported from Acelogic.
    lines = [
        "// <auto-generated by scripts/generate-lle-nid-registrations.py />",
        "// Copyright (C) 2026 SharpEmu Emulator Project",
        "// SPDX-License-Identifier: GPL-2.0-or-later",
        "//",
        f"// Ghidra {evidence['ghidra_version']} program: {evidence['program_name']}",
        f"// Analyzed provider SHA-256: {evidence['executable_sha256']}",
        "// Each registration prefers the loaded guest export. The shared HLE handler",
        "// is deliberately fail-closed and never claims provider behavior.",
        "",
        "using SharpEmu.HLE;",
        "",
        f"namespace {args.namespace};",
        "",
        f"public static class {args.class_name}",
        "{",
    ]
    # REUSE-IgnoreEnd
    for nid in sorted(by_nid):
        row = by_nid[nid]
        function = functions[nid]
        export_name = row.get("catalog_symbol") or function["symbol"]
        if int(function.get("function_body_addresses", 0)) > 0:
            body_measure = f"body addresses {function['function_body_addresses']}"
        else:
            body_measure = f"body bytes {function['function_body_bytes']}"
        lines.extend([
            f"    // Ghidra entry {function['function_entry']}; {body_measure}.",
            "    [SysAbiExport(",
            f"        Nid = {csharp_string(nid)},",
            f"        ExportName = {csharp_string(export_name)},",
            "        Target = Generation.Gen5,",
            f"        LibraryName = {csharp_string(args.library)},",
            "        PreferLle = true)]",
        ])
    lines.extend([
        "    public static int MissingGuestProvider(CpuContext ctx)",
        "    {",
        f"        if (string.Equals(Environment.GetEnvironmentVariable({csharp_string(args.log_env)}), \"1\", StringComparison.Ordinal))",
        "        {",
        "            Console.Error.WriteLine(" + csharp_string(
            "[LOADER][ERROR] " + (args.log_label or args.class_name) +
            " LLE-preferred export reached its fail-closed HLE fallback"
        ) + ");",
        "        }",
        "",
        "        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);",
        "    }",
        "}",
        "",
    ])

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines))
    print(
        f"generated={len(rows)} component={args.component} "
        f"provider_sha256={evidence['executable_sha256']} output={args.output}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
